environment:
  matrix:
    # MinGW
    # - TARGET: i686-pc-windows-gnu
    #   RUST_VERSION: nightly
    # - TARGET: x86_64-pc-windows-gnu
    #   RUST_VERSION: nightly

    # MSVC
    # - TARGET: i686-pc-windows-msvc
    #   RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: nightly

install:
  - ps: >-
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  # If you need to run additional steps during testing, they should be placed
  # inside this block
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo test --target %TARGET% &&
      cargo test --target %TARGET% --release
    )

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # release tag format is "vX.Y.Z"
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
