[package]
name = "qadapt"
version = "0.1.0"
authors = ["Bradlee Speice <bradlee@speice.io>"]
description = "The Quick And Dirty Allocation Profiling Tool"

[dependencies]
spin = "0.4"
libc = { version = "0.2", default-features = false }
