[package]

name = "qadapt-spin"
version = "1.0.1"
authors = [ "Mathijs van de Nes <git@mathijs.vd-nes.nl>",
            "John Ericson <John_Ericson@Yahoo.com>" ]
license = "MIT"
repository = "https://github.com/mvdnes/spin-rs.git"
documentation = "https://mvdnes.github.io/rust-docs/spin-rs/spin/index.html"
keywords = ["spinlock", "mutex", "rwlock"]
description = """
Synchronization primitives based on spinning.
They may contain data, are usable without `std`,
and static initializers are available.
"""
